# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1257, 610)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(100, 80))
        self.frame_toggle.setStyleSheet("")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet("QPushButton \n"
"{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border : 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"background-color: #f44335\n"
"\n"
";\n"
"}\n"
"")
        self.Btn_Toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design/icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Btn_Toggle.setIcon(icon)
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.label_5 = QtWidgets.QLabel(self.frame_top)
        self.label_5.setGeometry(QtCore.QRect(830, 10, 51, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("design/icons/esprit_small.png"))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.frame_top)
        self.label_4.setGeometry(QtCore.QRect(760, 9, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_34 = QtWidgets.QLabel(self.frame_top)
        self.label_34.setGeometry(QtCore.QRect(760, 32, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.frame_top_menus.setFont(font)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Btn_Menu_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Menu_2.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Menu_2.setFont(font)
        self.Btn_Menu_2.setStyleSheet("QPushButton \n"
"{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border : 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"background-color: #f44335\n"
"\n"
";\n"
"}\n"
"")
        self.Btn_Menu_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("design/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Btn_Menu_2.setIcon(icon1)
        self.Btn_Menu_2.setObjectName("Btn_Menu_2")
        self.verticalLayout_4.addWidget(self.Btn_Menu_2)
        self.Home = QtWidgets.QLabel(self.frame_top_menus)
        self.Home.setSizeIncrement(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Home.setFont(font)
        self.Home.setStyleSheet("color: rgb(255, 255, 255);")
        self.Home.setAlignment(QtCore.Qt.AlignCenter)
        self.Home.setObjectName("Home")
        self.verticalLayout_4.addWidget(self.Home)
        self.Btn_Menu_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Menu_1.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Menu_1.setFont(font)
        self.Btn_Menu_1.setStyleSheet("QPushButton \n"
"{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border : 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"background-color: #f44335\n"
"\n"
";\n"
"}\n"
"")
        self.Btn_Menu_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("design/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Btn_Menu_1.setIcon(icon2)
        self.Btn_Menu_1.setObjectName("Btn_Menu_1")
        self.verticalLayout_4.addWidget(self.Btn_Menu_1)
        self.Home_4 = QtWidgets.QLabel(self.frame_top_menus)
        self.Home_4.setSizeIncrement(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Home_4.setFont(font)
        self.Home_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.Home_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Home_4.setObjectName("Home_4")
        self.verticalLayout_4.addWidget(self.Home_4)
        self.Btn_Menu_3 = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Menu_3.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Menu_3.setFont(font)
        self.Btn_Menu_3.setAccessibleDescription("")
        self.Btn_Menu_3.setAutoFillBackground(False)
        self.Btn_Menu_3.setStyleSheet("QPushButton \n"
"{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border : 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"background-color:#f44335\n"
";\n"
"}\n"
"")
        self.Btn_Menu_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("design/icons/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Btn_Menu_3.setIcon(icon3)
        self.Btn_Menu_3.setObjectName("Btn_Menu_3")
        self.verticalLayout_4.addWidget(self.Btn_Menu_3)
        self.Home_2 = QtWidgets.QLabel(self.frame_top_menus)
        self.Home_2.setSizeIncrement(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Home_2.setFont(font)
        self.Home_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.Home_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Home_2.setObjectName("Home_2")
        self.verticalLayout_4.addWidget(self.Home_2)
        self.Btn_Menu_4 = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Menu_4.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Menu_4.setFont(font)
        self.Btn_Menu_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_Menu_4.setStyleSheet("QPushButton \n"
"{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border : 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"background-color: #f44335\n"
";\n"
"}\n"
"")
        self.Btn_Menu_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("design/icons/user-interface.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Btn_Menu_4.setIcon(icon4)
        self.Btn_Menu_4.setObjectName("Btn_Menu_4")
        self.verticalLayout_4.addWidget(self.Btn_Menu_4)
        self.Home_3 = QtWidgets.QLabel(self.frame_top_menus)
        self.Home_3.setSizeIncrement(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Home_3.setFont(font)
        self.Home_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.Home_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Home_3.setObjectName("Home_3")
        self.verticalLayout_4.addWidget(self.Home_3)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.Btn_Logout = QtWidgets.QPushButton(self.frame_left_menu)
        self.Btn_Logout.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Logout.setFont(font)
        self.Btn_Logout.setStyleSheet("QPushButton \n"
"{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border : 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"background-color: #de5758;\n"
"}\n"
"")
        self.Btn_Logout.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../.designer/backup/design/icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Btn_Logout.setIcon(icon5)
        self.Btn_Logout.setObjectName("Btn_Logout")
        self.verticalLayout_3.addWidget(self.Btn_Logout)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setStyleSheet("border-radius:20px")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.Pages_Widget.setFont(font)
        self.Pages_Widget.setStyleSheet("background-color:rgb(35, 35, 35);\n"
"border-radius:20px;")
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(260, 0, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(self.page_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 50, 361, 451))
        self.widget_3.setStyleSheet("background-color:#e9ecef\n"
";\n"
"border-radius:20px;")
        self.widget_3.setObjectName("widget_3")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(0, 80, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(30, 170, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(30, 240, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(30, 290, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.hour_spinBox = QtWidgets.QSpinBox(self.widget_3)
        self.hour_spinBox.setGeometry(QtCore.QRect(250, 250, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.hour_spinBox.setFont(font)
        self.hour_spinBox.setStyleSheet("QSpinBox {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"")
        self.hour_spinBox.setObjectName("hour_spinBox")
        self.supervisors_spinBox = QtWidgets.QSpinBox(self.widget_3)
        self.supervisors_spinBox.setGeometry(QtCore.QRect(250, 300, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.supervisors_spinBox.setFont(font)
        self.supervisors_spinBox.setStyleSheet("QSpinBox {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.supervisors_spinBox.setObjectName("supervisors_spinBox")
        self.examdate_label = QtWidgets.QLabel(self.widget_3)
        self.examdate_label.setGeometry(QtCore.QRect(220, 180, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.examdate_label.setFont(font)
        self.examdate_label.setAlignment(QtCore.Qt.AlignCenter)
        self.examdate_label.setObjectName("examdate_label")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(60, 210, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.submit_btn = QtWidgets.QPushButton(self.widget_3)
        self.submit_btn.setGeometry(QtCore.QRect(20, 350, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.submit_btn.setFont(font)
        self.submit_btn.setStyleSheet("\n"
"QPushButton#submit_btn\n"
"{\n"
"background-color :#eb2f30;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#submit_btn:pressed\n"
"{\n"
"background-color :#de5758;  \n"
"}")
        self.submit_btn.setObjectName("submit_btn")
        self.close_add_exam = QtWidgets.QPushButton(self.widget_3)
        self.close_add_exam.setGeometry(QtCore.QRect(320, 20, 25, 23))
        self.close_add_exam.setStyleSheet("border-radius : 10px solid;\n"
"border:2px solid black;")
        self.close_add_exam.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("design/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.close_add_exam.setIcon(icon6)
        self.close_add_exam.setObjectName("close_add_exam")
        self.widget_4 = QtWidgets.QWidget(self.page_2)
        self.widget_4.setGeometry(QtCore.QRect(10, 50, 861, 451))
        self.widget_4.setStyleSheet("background-color:#e9ecef\n"
";\n"
"border-radius:20px;")
        self.widget_4.setObjectName("widget_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget_4)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 80, 371, 251))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("color:black;\n"
"border-radius:20px;")
        self.calendarWidget.setObjectName("calendarWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_4)
        self.tableWidget.setGeometry(QtCore.QRect(409, 80, 431, 241))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("/* General QTableWidget styling */\n"
"QTableWidget {\n"
"    border-radius: 5px;\n"
"    gridline-color: #f44335;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"    background-color: #e9ecef;\n"
"}\n"
"\n"
"/* Header styling */\n"
"QHeaderView::section {\n"
"    background-color: #f44335;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: 1px solid #f44335;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Alternate row colors */\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #f44335;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #fdd2d2;\n"
"}\n"
"\n"
"/* Grid lines */\n"
"QTableWidget::item {\n"
"    border: 1px solid #f44335;\n"
"}\n"
"\n"
"/* Vertical and Horizontal Scrollbar */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #e0e0e0;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #f44335;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #e0e0e0;\n"
"    height: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #f44335;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Corner button */\n"
"QTableCornerButton::section {\n"
"    background-color: #f44335;\n"
"    border: 1px solid #f44335;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setGeometry(QtCore.QRect(520, 10, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.add_exam_btn = QtWidgets.QPushButton(self.widget_4)
        self.add_exam_btn.setGeometry(QtCore.QRect(10, 350, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.add_exam_btn.setFont(font)
        self.add_exam_btn.setStyleSheet("\n"
"QPushButton#add_exam_btn\n"
"{\n"
"background-color: #03a9f4;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#add_exam_btn:pressed\n"
"{\n"
"background-color :#21b5f4;  \n"
"}")
        self.add_exam_btn.setIcon(icon2)
        self.add_exam_btn.setObjectName("add_exam_btn")
        self.delete_exam_btn = QtWidgets.QPushButton(self.widget_4)
        self.delete_exam_btn.setGeometry(QtCore.QRect(510, 350, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.delete_exam_btn.setFont(font)
        self.delete_exam_btn.setStyleSheet("\n"
"QPushButton#delete_exam_btn\n"
"{\n"
"background-color :#f44335;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#delete_exam_btn:pressed\n"
"{\n"
"background-color :#de5758;  \n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("design/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.delete_exam_btn.setIcon(icon7)
        self.delete_exam_btn.setObjectName("delete_exam_btn")
        self.widget_3.raise_()
        self.label.raise_()
        self.widget_4.raise_()
        self.Pages_Widget.addWidget(self.page_2)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.widget_2 = QtWidgets.QWidget(self.page_1)
        self.widget_2.setGeometry(QtCore.QRect(390, 50, 481, 451))
        self.widget_2.setStyleSheet("background-color:#e9ecef\n"
";\n"
"border-radius:20px;")
        self.widget_2.setObjectName("widget_2")
        self.change_prof_status = QtWidgets.QPushButton(self.widget_2)
        self.change_prof_status.setGeometry(QtCore.QRect(350, 370, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.change_prof_status.setFont(font)
        self.change_prof_status.setStyleSheet("\n"
"QPushButton#change_prof_status\n"
"{\n"
"background-color: #03a9f4;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#change_prof_status:pressed\n"
"{\n"
"background-color :#4f93ff;  \n"
"}")
        self.change_prof_status.setObjectName("change_prof_status")
        self.label_29 = QtWidgets.QLabel(self.widget_2)
        self.label_29.setGeometry(QtCore.QRect(0, 360, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.widget_2)
        self.label_30.setGeometry(QtCore.QRect(20, 385, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.widget_2)
        self.label_31.setGeometry(QtCore.QRect(20, 40, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.widget_2)
        self.label_32.setGeometry(QtCore.QRect(10, 240, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("")
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.widget_2)
        self.label_33.setGeometry(QtCore.QRect(10, 270, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("")
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.sat_spinbox = QtWidgets.QSpinBox(self.widget_2)
        self.sat_spinbox.setGeometry(QtCore.QRect(350, 240, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.sat_spinbox.setFont(font)
        self.sat_spinbox.setStyleSheet("QSpinBox {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"")
        self.sat_spinbox.setObjectName("sat_spinbox")
        self.submit_saturdays_btn = QtWidgets.QPushButton(self.widget_2)
        self.submit_saturdays_btn.setGeometry(QtCore.QRect(350, 270, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.submit_saturdays_btn.setFont(font)
        self.submit_saturdays_btn.setStyleSheet("\n"
"QPushButton#submit_saturdays_btn\n"
"{\n"
"background-color: #fb8c00;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#submit_saturdays_btn:pressed\n"
"{\n"
"background-color :#fb9118;  \n"
"}")
        self.submit_saturdays_btn.setObjectName("submit_saturdays_btn")
        self.label_39 = QtWidgets.QLabel(self.widget_2)
        self.label_39.setGeometry(QtCore.QRect(10, 140, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("")
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.notify_all_professors = QtWidgets.QPushButton(self.widget_2)
        self.notify_all_professors.setGeometry(QtCore.QRect(350, 140, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.notify_all_professors.setFont(font)
        self.notify_all_professors.setStyleSheet("\n"
"QPushButton#notify_all_professors\n"
"{\n"
"background-color: #f44335;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#notify_all_professors:pressed\n"
"{\n"
"background-color :#fb9118;  \n"
"}")
        self.notify_all_professors.setObjectName("notify_all_professors")
        self.label_12 = QtWidgets.QLabel(self.page_1)
        self.label_12.setGeometry(QtCore.QRect(380, 0, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.widget_5 = QtWidgets.QWidget(self.page_1)
        self.widget_5.setGeometry(QtCore.QRect(30, 270, 171, 231))
        self.widget_5.setStyleSheet("background-color:#03a9f4\n"
";\n"
"border-radius:20px;")
        self.widget_5.setObjectName("widget_5")
        self.label_25 = QtWidgets.QLabel(self.widget_5)
        self.label_25.setGeometry(QtCore.QRect(0, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.widget_5)
        self.label_26.setGeometry(QtCore.QRect(10, 190, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.prof_scheduling_label = QtWidgets.QLabel(self.widget_5)
        self.prof_scheduling_label.setGeometry(QtCore.QRect(0, 20, 171, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(51)
        font.setBold(True)
        font.setWeight(75)
        self.prof_scheduling_label.setFont(font)
        self.prof_scheduling_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.prof_scheduling_label.setText("")
        self.prof_scheduling_label.setAlignment(QtCore.Qt.AlignCenter)
        self.prof_scheduling_label.setObjectName("prof_scheduling_label")
        self.widget_7 = QtWidgets.QWidget(self.page_1)
        self.widget_7.setGeometry(QtCore.QRect(30, 50, 171, 211))
        self.widget_7.setStyleSheet("background-color:#e91e63;\n"
"border-radius:20px;")
        self.widget_7.setObjectName("widget_7")
        self.label_22 = QtWidgets.QLabel(self.widget_7)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.users_count_label = QtWidgets.QLabel(self.widget_7)
        self.users_count_label.setGeometry(QtCore.QRect(0, 10, 171, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(51)
        font.setBold(True)
        font.setWeight(75)
        self.users_count_label.setFont(font)
        self.users_count_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.users_count_label.setText("")
        self.users_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.users_count_label.setObjectName("users_count_label")
        self.widget_8 = QtWidgets.QWidget(self.page_1)
        self.widget_8.setGeometry(QtCore.QRect(210, 50, 171, 211))
        self.widget_8.setStyleSheet("background-color:#f44335\n"
";\n"
"border-radius:20px;")
        self.widget_8.setObjectName("widget_8")
        self.label_23 = QtWidgets.QLabel(self.widget_8)
        self.label_23.setGeometry(QtCore.QRect(10, 145, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_8)
        self.label_24.setGeometry(QtCore.QRect(10, 175, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.has_planning_label = QtWidgets.QLabel(self.widget_8)
        self.has_planning_label.setGeometry(QtCore.QRect(0, 10, 171, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(51)
        font.setBold(True)
        font.setWeight(75)
        self.has_planning_label.setFont(font)
        self.has_planning_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.has_planning_label.setText("")
        self.has_planning_label.setAlignment(QtCore.Qt.AlignCenter)
        self.has_planning_label.setObjectName("has_planning_label")
        self.widget_9 = QtWidgets.QWidget(self.page_1)
        self.widget_9.setGeometry(QtCore.QRect(210, 270, 171, 231))
        self.widget_9.setStyleSheet("background-color:#fb8c00\n"
";\n"
"border-radius:20px;")
        self.widget_9.setObjectName("widget_9")
        self.label_27 = QtWidgets.QLabel(self.widget_9)
        self.label_27.setGeometry(QtCore.QRect(0, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget_9)
        self.label_28.setGeometry(QtCore.QRect(10, 190, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.fixed_saturdays_label = QtWidgets.QLabel(self.widget_9)
        self.fixed_saturdays_label.setGeometry(QtCore.QRect(0, 20, 171, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(51)
        font.setBold(True)
        font.setWeight(75)
        self.fixed_saturdays_label.setFont(font)
        self.fixed_saturdays_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.fixed_saturdays_label.setText("")
        self.fixed_saturdays_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fixed_saturdays_label.setObjectName("fixed_saturdays_label")
        self.Pages_Widget.addWidget(self.page_1)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.statistics_widget = QtWidgets.QWidget(self.page_3)
        self.statistics_widget.setGeometry(QtCore.QRect(659, 50, 211, 451))
        self.statistics_widget.setStyleSheet("background-color:#e9ecef\n"
";\n"
"border-radius:20px;")
        self.statistics_widget.setObjectName("statistics_widget")
        self.label_2 = QtWidgets.QLabel(self.statistics_widget)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 791, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.professors_combobox = QtWidgets.QComboBox(self.statistics_widget)
        self.professors_combobox.setGeometry(QtCore.QRect(290, 220, 251, 41))
        self.professors_combobox.setStyleSheet("/* General QComboBox styling */\n"
"QComboBox {\n"
"    border: 1px solid #eb2f30;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #ffffff;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* QComboBox when the drop-down is open */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #eb2f30;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-color: #eb2f30;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png); /* Replace with your own arrow image */\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"/* QComboBox Popup styling */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #eb2f30;\n"
"    selection-background-color: #eb2f30;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"/* Optional: Customize the QComboBox when it\'s disabled */\n"
"QComboBox:disabled {\n"
"    background-color: #d3d3d3;\n"
"    color: #a0a0a0;\n"
"    border: 1px solid #d3d3d3;\n"
"}\n"
"")
        self.professors_combobox.setObjectName("professors_combobox")
        self.label_3 = QtWidgets.QLabel(self.statistics_widget)
        self.label_3.setGeometry(QtCore.QRect(60, 30, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_17 = QtWidgets.QLabel(self.statistics_widget)
        self.label_17.setGeometry(QtCore.QRect(5, 100, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.statistics_widget)
        self.label_18.setGeometry(QtCore.QRect(5, 180, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.statistics_widget)
        self.label_19.setGeometry(QtCore.QRect(5, 260, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.statistics_widget)
        self.label_20.setGeometry(QtCore.QRect(10, 340, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.l1 = QtWidgets.QLabel(self.statistics_widget)
        self.l1.setGeometry(QtCore.QRect(10, 140, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setText("")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.statistics_widget)
        self.l2.setGeometry(QtCore.QRect(10, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setText("")
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.statistics_widget)
        self.l3.setGeometry(QtCore.QRect(10, 290, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setText("")
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.statistics_widget)
        self.l4.setGeometry(QtCore.QRect(10, 370, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.l4.setFont(font)
        self.l4.setText("")
        self.l4.setAlignment(QtCore.Qt.AlignCenter)
        self.l4.setObjectName("l4")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(360, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.prof_details_widget = QtWidgets.QWidget(self.page_3)
        self.prof_details_widget.setGeometry(QtCore.QRect(20, 50, 621, 451))
        self.prof_details_widget.setStyleSheet("background-color:#e9ecef\n"
";\n"
"border-radius:20px;")
        self.prof_details_widget.setObjectName("prof_details_widget")
        self.label_13 = QtWidgets.QLabel(self.prof_details_widget)
        self.label_13.setGeometry(QtCore.QRect(30, 10, 541, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.close_stats_details = QtWidgets.QPushButton(self.prof_details_widget)
        self.close_stats_details.setGeometry(QtCore.QRect(580, 20, 25, 23))
        self.close_stats_details.setStyleSheet("border-radius : 10px solid;\n"
"border:2px solid black;")
        self.close_stats_details.setText("")
        self.close_stats_details.setIcon(icon6)
        self.close_stats_details.setObjectName("close_stats_details")
        self.notchosen_widget = QtWidgets.QWidget(self.prof_details_widget)
        self.notchosen_widget.setGeometry(QtCore.QRect(70, 120, 541, 231))
        self.notchosen_widget.setObjectName("notchosen_widget")
        self.label_21 = QtWidgets.QLabel(self.notchosen_widget)
        self.label_21.setGeometry(QtCore.QRect(40, 70, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.notify = QtWidgets.QPushButton(self.notchosen_widget)
        self.notify.setGeometry(QtCore.QRect(290, 170, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.notify.setFont(font)
        self.notify.setStyleSheet("\n"
"QPushButton#notify\n"
"{\n"
"background-color :#e91e63;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#notify:pressed\n"
"{\n"
"background-color :#de5758;  \n"
"}")
        self.notify.setObjectName("notify")
        self.chosen_widget = QtWidgets.QWidget(self.prof_details_widget)
        self.chosen_widget.setGeometry(QtCore.QRect(10, 50, 591, 391))
        self.chosen_widget.setObjectName("chosen_widget")
        self.planning_table = QtWidgets.QTableWidget(self.chosen_widget)
        self.planning_table.setGeometry(QtCore.QRect(130, 10, 341, 301))
        self.planning_table.setStyleSheet("/* General QTableWidget styling */\n"
"QTableWidget {\n"
"    border-radius: 5px;\n"
"    gridline-color: #f44335;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"    background-color: #e9ecef;\n"
"}\n"
"\n"
"/* Header styling */\n"
"QHeaderView::section {\n"
"    background-color: #f44335;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: 1px solid #f44335;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Alternate row colors */\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #f44335;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #fdd2d2;\n"
"}\n"
"\n"
"/* Grid lines */\n"
"QTableWidget::item {\n"
"    border: 1px solid #f44335;\n"
"}\n"
"\n"
"/* Vertical and Horizontal Scrollbar */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #e0e0e0;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #f44335;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #e0e0e0;\n"
"    height: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #f44335;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Corner button */\n"
"QTableCornerButton::section {\n"
"    background-color: #f44335;\n"
"    border: 1px solid #f44335;\n"
"}\n"
"")
        self.planning_table.setObjectName("planning_table")
        self.planning_table.setColumnCount(3)
        self.planning_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.planning_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.planning_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.planning_table.setHorizontalHeaderItem(2, item)
        self.add_supervision_btn = QtWidgets.QPushButton(self.chosen_widget)
        self.add_supervision_btn.setGeometry(QtCore.QRect(150, 320, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.add_supervision_btn.setFont(font)
        self.add_supervision_btn.setStyleSheet("\n"
"QPushButton#add_supervision_btn\n"
"{\n"
"background-color: #03a9f4;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#add_supervision_btn:pressed\n"
"{\n"
"background-color :#21b5f4;  \n"
"}")
        self.add_supervision_btn.setText("")
        self.add_supervision_btn.setIcon(icon2)
        self.add_supervision_btn.setObjectName("add_supervision_btn")
        self.update_supervision_btn = QtWidgets.QPushButton(self.chosen_widget)
        self.update_supervision_btn.setGeometry(QtCore.QRect(240, 320, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.update_supervision_btn.setFont(font)
        self.update_supervision_btn.setStyleSheet("\n"
"QPushButton#update_supervision_btn\n"
"{\n"
"background-color: #fb8c00;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#update_supervision_btn:pressed\n"
"{\n"
"background-color :#fba50e;  \n"
"}")
        self.update_supervision_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("design/icons/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.update_supervision_btn.setIcon(icon8)
        self.update_supervision_btn.setObjectName("update_supervision_btn")
        self.delete_supervision_btn = QtWidgets.QPushButton(self.chosen_widget)
        self.delete_supervision_btn.setGeometry(QtCore.QRect(330, 320, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.delete_supervision_btn.setFont(font)
        self.delete_supervision_btn.setStyleSheet("\n"
"QPushButton#delete_supervision_btn\n"
"{\n"
"background-color: #f44335;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#delete_supervision_btn:pressed\n"
"{\n"
"background-color :#fb9118;  \n"
"}")
        self.delete_supervision_btn.setText("")
        self.delete_supervision_btn.setIcon(icon7)
        self.delete_supervision_btn.setObjectName("delete_supervision_btn")
        self.exam_manager_frame = QtWidgets.QFrame(self.prof_details_widget)
        self.exam_manager_frame.setEnabled(True)
        self.exam_manager_frame.setGeometry(QtCore.QRect(140, 411, 321, 20))
        self.exam_manager_frame.setAutoFillBackground(False)
        self.exam_manager_frame.setStyleSheet("border-radius : 10px solid;\n"
"border:2px solid black;\n"
"")
        self.exam_manager_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exam_manager_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exam_manager_frame.setLineWidth(12)
        self.exam_manager_frame.setObjectName("exam_manager_frame")
        self.label_35 = QtWidgets.QLabel(self.exam_manager_frame)
        self.label_35.setGeometry(QtCore.QRect(40, 30, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("border:2px solid white;\n"
"")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.close_exam_manager = QtWidgets.QPushButton(self.exam_manager_frame)
        self.close_exam_manager.setGeometry(QtCore.QRect(285, 10, 25, 23))
        self.close_exam_manager.setStyleSheet("border-radius : 10px solid;\n"
"border:2px solid black;")
        self.close_exam_manager.setText("")
        self.close_exam_manager.setIcon(icon6)
        self.close_exam_manager.setObjectName("close_exam_manager")
        self.submit_exam_btn = QtWidgets.QPushButton(self.exam_manager_frame)
        self.submit_exam_btn.setGeometry(QtCore.QRect(100, 330, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.submit_exam_btn.setFont(font)
        self.submit_exam_btn.setStyleSheet("\n"
"QPushButton#accept_btn\n"
"{\n"
"background-color: #4caf50\n"
";  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#accept_btn:pressed\n"
"{\n"
"background-color :#55ff7f;  \n"
"}")
        self.submit_exam_btn.setObjectName("submit_exam_btn")
        self.prof_details_widget.raise_()
        self.label_14.raise_()
        self.statistics_widget.raise_()
        self.Pages_Widget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.widget_6 = QtWidgets.QWidget(self.page_4)
        self.widget_6.setGeometry(QtCore.QRect(10, 50, 861, 451))
        self.widget_6.setStyleSheet("background-color:#e9ecef\n"
";\n"
"border-radius:20px;")
        self.widget_6.setObjectName("widget_6")
        self.complaints_table = QtWidgets.QTableWidget(self.widget_6)
        self.complaints_table.setGeometry(QtCore.QRect(30, 30, 801, 351))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.complaints_table.setFont(font)
        self.complaints_table.setStyleSheet("/* General QTableWidget styling */\n"
"QTableWidget {\n"
"    border-radius: 5px;\n"
"    gridline-color: #f44335;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"    background-color: #e9ecef;\n"
"}\n"
"\n"
"/* Header styling */\n"
"QHeaderView::section {\n"
"    background-color: #f44335;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: 1px solid #f44335;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Alternate row colors */\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #f44335;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #fdd2d2;\n"
"}\n"
"\n"
"/* Grid lines */\n"
"QTableWidget::item {\n"
"    border: 1px solid #f44335;\n"
"}\n"
"\n"
"/* Vertical and Horizontal Scrollbar */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #e0e0e0;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #f44335;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #e0e0e0;\n"
"    height: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #f44335;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Corner button */\n"
"QTableCornerButton::section {\n"
"    background-color: #f44335;\n"
"    border: 1px solid #f44335;\n"
"}\n"
"")
        self.complaints_table.setLineWidth(1)
        self.complaints_table.setDragEnabled(False)
        self.complaints_table.setColumnCount(6)
        self.complaints_table.setObjectName("complaints_table")
        self.complaints_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.complaints_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaints_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaints_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaints_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaints_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaints_table.setHorizontalHeaderItem(5, item)
        self.resolution_message_frame = QtWidgets.QFrame(self.widget_6)
        self.resolution_message_frame.setEnabled(True)
        self.resolution_message_frame.setGeometry(QtCore.QRect(290, 70, 321, 271))
        self.resolution_message_frame.setAutoFillBackground(False)
        self.resolution_message_frame.setStyleSheet("border-radius : 10px solid;\n"
"border:2px solid black;\n"
"")
        self.resolution_message_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resolution_message_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resolution_message_frame.setLineWidth(12)
        self.resolution_message_frame.setObjectName("resolution_message_frame")
        self.resolution_field = QtWidgets.QTextEdit(self.resolution_message_frame)
        self.resolution_field.setGeometry(QtCore.QRect(30, 80, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.resolution_field.setFont(font)
        self.resolution_field.setStyleSheet("background-color : white")
        self.resolution_field.setObjectName("resolution_field")
        self.label_16 = QtWidgets.QLabel(self.resolution_message_frame)
        self.label_16.setGeometry(QtCore.QRect(40, 30, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border:2px solid white;\n"
"")
        self.label_16.setObjectName("label_16")
        self.close_resolution_frame = QtWidgets.QPushButton(self.resolution_message_frame)
        self.close_resolution_frame.setGeometry(QtCore.QRect(285, 10, 25, 23))
        self.close_resolution_frame.setStyleSheet("border-radius : 10px solid;\n"
"border:2px solid black;")
        self.close_resolution_frame.setText("")
        self.close_resolution_frame.setIcon(icon6)
        self.close_resolution_frame.setObjectName("close_resolution_frame")
        self.reject_btn = QtWidgets.QPushButton(self.resolution_message_frame)
        self.reject_btn.setGeometry(QtCore.QRect(170, 200, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.reject_btn.setFont(font)
        self.reject_btn.setStyleSheet("\n"
"QPushButton#reject_btn\n"
"{\n"
"background-color :#f44335\n"
";  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#reject_btn:pressed\n"
"{\n"
"background-color :#de5758;  \n"
"}")
        self.reject_btn.setObjectName("reject_btn")
        self.accept_btn = QtWidgets.QPushButton(self.resolution_message_frame)
        self.accept_btn.setGeometry(QtCore.QRect(40, 200, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.accept_btn.setFont(font)
        self.accept_btn.setStyleSheet("\n"
"QPushButton#accept_btn\n"
"{\n"
"background-color: #4caf50\n"
";  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#accept_btn:pressed\n"
"{\n"
"background-color :#55ff7f;  \n"
"}")
        self.accept_btn.setObjectName("accept_btn")
        self.resolve_btn = QtWidgets.QPushButton(self.widget_6)
        self.resolve_btn.setGeometry(QtCore.QRect(380, 390, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.resolve_btn.setFont(font)
        self.resolve_btn.setStyleSheet("\n"
"QPushButton#resolve_btn\n"
"{\n"
"background-color: #03a9f4;  \n"
"color :white;\n"
"border-radius : 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#resolve_btn:pressed\n"
"{\n"
"background-color :#4f93ff;  \n"
"}")
        self.resolve_btn.setObjectName("resolve_btn")
        self.label_15 = QtWidgets.QLabel(self.page_4)
        self.label_15.setGeometry(QtCore.QRect(250, 0, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.Pages_Widget.addWidget(self.page_4)
        self.verticalLayout_5.addWidget(self.Pages_Widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_Widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Esprit"))
        self.label_34.setText(_translate("MainWindow", "Planner"))
        self.Home.setText(_translate("MainWindow", "Home"))
        self.Home_4.setText(_translate("MainWindow", "Add Planning"))
        self.Home_2.setText(_translate("MainWindow", "Statistics"))
        self.Home_3.setText(_translate("MainWindow", "Complaints"))
        self.label.setText(_translate("MainWindow", "Exam Calendar Manager"))
        self.label_6.setText(_translate("MainWindow", "Exam Date Manager"))
        self.label_7.setText(_translate("MainWindow", "Exam Date "))
        self.label_8.setText(_translate("MainWindow", "Exam start hour"))
        self.label_9.setText(_translate("MainWindow", "Required supervisors"))
        self.examdate_label.setText(_translate("MainWindow", "NA"))
        self.label_10.setText(_translate("MainWindow", "( Pick a date from the calendar)"))
        self.submit_btn.setText(_translate("MainWindow", "Submit"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Exam Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Passage Hour "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Superivisors Required"))
        self.label_11.setText(_translate("MainWindow", "Exams list"))
        self.add_exam_btn.setText(_translate("MainWindow", "Add Exam"))
        self.delete_exam_btn.setText(_translate("MainWindow", "Delete "))
        self.change_prof_status.setText(_translate("MainWindow", "Change "))
        self.label_29.setText(_translate("MainWindow", "Click Here to Lock / Unlock Professor Scheduling "))
        self.label_30.setText(_translate("MainWindow", "Note : Unlock Scheduling after finishing the entire exams planification"))
        self.label_31.setText(_translate("MainWindow", "General Settings"))
        self.label_32.setText(_translate("MainWindow", "Fix the number of auto affected Saturdays "))
        self.label_33.setText(_translate("MainWindow", "Supervisons for every professor "))
        self.submit_saturdays_btn.setText(_translate("MainWindow", "Submit"))
        self.label_39.setText(_translate("MainWindow", "Notify Profeesors Who don\'t have a plannings yet"))
        self.notify_all_professors.setText(_translate("MainWindow", "Notify"))
        self.label_12.setText(_translate("MainWindow", "Home"))
        self.label_25.setText(_translate("MainWindow", "Professors Scheduling"))
        self.label_26.setText(_translate("MainWindow", "Locker"))
        self.label_22.setText(_translate("MainWindow", "Users Count"))
        self.label_23.setText(_translate("MainWindow", "Users That have "))
        self.label_24.setText(_translate("MainWindow", "a Planning"))
        self.label_27.setText(_translate("MainWindow", "Fixed Saturdays "))
        self.label_28.setText(_translate("MainWindow", "Supervisions"))
        self.label_2.setText(_translate("MainWindow", "Please Select The Desired professor to see it\'s full planning"))
        self.label_3.setText(_translate("MainWindow", "User Details"))
        self.label_17.setText(_translate("MainWindow", "Identifier"))
        self.label_18.setText(_translate("MainWindow", "Full Name"))
        self.label_19.setText(_translate("MainWindow", "Email"))
        self.label_20.setText(_translate("MainWindow", "Phone Number"))
        self.label_14.setText(_translate("MainWindow", "Statistics"))
        self.label_21.setText(_translate("MainWindow", "This User has not chosen a Planning yet"))
        self.notify.setText(_translate("MainWindow", "Notify Professor via an Email"))
        item = self.planning_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.planning_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Supervision Date"))
        item = self.planning_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Hour"))
        self.label_35.setText(_translate("MainWindow", "Exam Manager"))
        self.submit_exam_btn.setText(_translate("MainWindow", "Submit"))
        item = self.complaints_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Identifier"))
        item = self.complaints_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Submission Date"))
        item = self.complaints_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Submission Message"))
        item = self.complaints_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.complaints_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Resolution Date"))
        item = self.complaints_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resolution Message"))
        self.label_16.setText(_translate("MainWindow", "Resolution message"))
        self.reject_btn.setText(_translate("MainWindow", "Reject"))
        self.accept_btn.setText(_translate("MainWindow", "Accept"))
        self.resolve_btn.setText(_translate("MainWindow", "Resolve"))
        self.label_15.setText(_translate("MainWindow", "Professors Complaints"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
